
// Objective-C API for talking to the following Go packages
//
//	novakeykembridge/novakeykem
//
// File is generated by gomobile bind. Do not edit.
#ifndef __NovaKeyKEM_FRAMEWORK_H__
#define __NovaKeyKEM_FRAMEWORK_H__

#include "Novakeykem.objc.h"
#include "Universe.objc.h"

#endif
