// Objective-C API for talking to novakeykembridge/novakeykem Go package.
//   gobind -lang=objc novakeykembridge/novakeykem
//
// File is generated by gobind. Do not edit.

#ifndef __Novakeykem_H__
#define __Novakeykem_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSData* _Nullable NovakeykemBuildApproveFrame(NSString* _Nullable pairingBlobJSON, NSError* _Nullable* _Nullable error);

/**
 * BuildArmFrame builds a v3 frame with inner msgType=3 and payload JSON: {"ms": <durationMs>}
 */
FOUNDATION_EXPORT NSData* _Nullable NovakeykemBuildArmFrame(NSString* _Nullable pairingBlobJSON, long durationMs, NSError* _Nullable* _Nullable error);

/**
 * BuildDisarmFrame builds a v3 frame with inner msgType=4 and empty payload.
 */
FOUNDATION_EXPORT NSData* _Nullable NovakeykemBuildDisarmFrame(NSString* _Nullable pairingBlobJSON, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable NovakeykemBuildInjectFrame(NSString* _Nullable pairingBlobJSON, NSString* _Nullable secret, NSError* _Nullable* _Nullable error);

/**
 * BuildPairRegisterBundle returns a packed blob:

[u32 frameLen][frameBytes][u16 kemCtLen][kemCt][32 aeadKey]

- frameBytes is exactly what your daemon expects after server_key:
  ctLen(u16) + ct + nonce(24) + ciphertext

- kemCt is needed as AAD input for ack decrypt ("PAIR"+ct+ackNonce)
- aeadKey is needed to decrypt ack (XChaCha20-Poly1305)
 */
FOUNDATION_EXPORT NSData* _Nullable NovakeykemBuildPairRegisterBundle(NSString* _Nullable serverKeyJSON, NSString* _Nullable tokenRawURLB64, NSString* _Nullable deviceID, NSString* _Nullable deviceKeyHex, NSError* _Nullable* _Nullable error);

/**
 * DecryptPairAck validates and decrypts daemon ack.
ack is: [24-byte ackNonce][ciphertext]
 */
FOUNDATION_EXPORT NSString* _Nonnull NovakeykemDecryptPairAck(NSData* _Nullable ack, NSData* _Nullable registerCT, NSData* _Nullable aeadKey, NSError* _Nullable* _Nullable error);

#endif
