// Objective-C API for talking to novakeykembridge Go package.
//   gobind -lang=objc novakeykembridge
//
// File is generated by gobind. Do not edit.

#ifndef __Novakeykembridge_H__
#define __Novakeykembridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Version returns the bridge version (sanity check export).
 */
FOUNDATION_EXPORT NSString* _Nonnull NovakeykembridgeVersion(void);

#endif
