// Objective-C API for talking to novakeykembridge/novakeykem Go package.
//   gobind -lang=objc novakeykembridge/novakeykem
//
// File is generated by gobind. Do not edit.

#ifndef __Novakeykem_H__
#define __Novakeykem_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSData* _Nullable NovakeykemBuildApproveFrame(NSString* _Nullable pairingBlobJSON, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable NovakeykemBuildInjectFrame(NSString* _Nullable pairingBlobJSON, NSString* _Nullable secret, NSError* _Nullable* _Nullable error);

#endif
